function citations = CO2flux_citations(refs)
%CO2flux_citations Get literature citations from reference codes.
% Part of the CO2flux toolbox [https://github.com/mvdh7/CO2flux].
% Written by Matthew P. Humphreys [v1.0.0, last updated 2019-11-22].
% Input:
%   refs = String or cell of strings of reference codes.
% Output:
%   citations = Cell of strings of full citations corresponding to the
%               input ref codes.
if isa(refs, 'char')
    refs = {refs};
end % if
citations = cell(size(refs));
for R = 1:numel(citations)
    switch refs{R}
        case 'KRP06'
            citations{R} = ['Krakauer, N. Y., Randerson, J. T., ' ...
                'Primeau, F. W., Gruber, N., and Menemenlis, D. ' ...
                '(2006). Carbon isotope evidence for the latitudinal ' ...
                'distribution and wind speed dependence of the air–' ...
                'sea gas transfer velocity. Tellus B 58, 390–417. ' ...
                'doi:10.1111/j.1600-0889.2006.00223.x.'];
        case 'NML00'
            citations{R} = ['Nightingale, P. D., Malin, G., Law, C. ' ...
                'S., Watson, A. J., Liss, P. S., Liddicoat, M. I., ' ...
                'Boutin, J., and Upstill-Goddard, R. C. (2000). In ' ...
                'situ evaluation of air-sea gas exchange ' ...
                'parameterizations using novel conservative and ' ...
                'volatile tracers. Global Biogeochemical Cycles 14, ' ...
                '373–388. doi:10.1029/1999GB900091.'];
        case 'RBHW19'
            citations{R} = ['Ribas-Ribas, M., Battaglia, G., ' ...
                'Humphreys, M. P., and Wurl, O. (2019). Impact of ' ...
                'Nonzero Intercept Gas Transfer Velocity ' ...
                'Parameterizations on Global and Regional Ocean–' ...
                'Atmosphere CO2 Fluxes. Geosciences 9, 230. ' ...
                'doi:10.3390/geosciences9050230.'];
        case 'TSW09'
            citations{R} = ['Takahashi, T., Sutherland, S. C., ' ...
                'Wanninkhof, R., Sweeney, C., Feely, R. A., Chipman, ' ...
                'D. W., et al. (2009). Climatological mean and ' ...
                'decadal change in surface ocean pCO2, and net sea–' ...
                'air CO2 flux over the global oceans. Deep-Sea ' ...
                'Research Part II 56, 554–577. ' ...
                'doi:10.1016/j.dsr2.2008.12.009.'];
        case 'W92'
            citations{R} = ['Wanninkhof, R. (1992). Relationship ' ...
                'Between Wind Speed and Gas Exchange Over the Ocean. ' ...
                'Journal of Geophysical Research 97, 7373–7382. ' ...
                'doi:10.1029/92JC00188.'];
        case 'W14'
            citations{R} = ['Wanninkhof, R. (2014). Relationship ' ...
                'between wind speed and gas exchange over the ocean ' ...
                'revisited: Gas exchange and wind speed over the ' ...
                'ocean. Limnology and Oceanography Methods 12, ' ...
                '351–362. doi:10.4319/lom.2014.12.351.'];
        case 'W74'
            citations{R} = ['Weiss, R. F. (1974). Carbon dioxide in ' ...
                'water and seawater: the solubility of a non-ideal ' ...
                'gas. Marine Chemistry 2, 203–215. ' ...
                'doi:10.1016/0304-4203(74)90015-2.'];
    end % switch
end % for R
